version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/UI"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "laravel/framework"
