name: Node.js Tests

on:
  push:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm run ci
      - run: npm run test
