name: Split commits

on:
  push:
    branches: ['3.x']

concurrency:
  group: split

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - { namespace: UI, repo: ui }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          repo_url="https://${{ secrets.SUPER_ACCESS_TOKEN }}@github.com/moonshine-software/${{ matrix.package.repo }}.git"
          git remote add subtree "$repo_url"
          git fetch subtree ${{ github.ref_name }}
      - run: |
          git subtree pull --prefix src/${{ matrix.package.namespace }} subtree ${{ github.ref_name }} --squash --allow-unrelated-histories
      - run: |
          repo_url="https://${{ secrets.SUPER_ACCESS_TOKEN }}@github.com/moonshine-software/${{ matrix.package.repo }}.git"
          git subtree push --prefix src/${{ matrix.package.namespace }} "$repo_url" ${{ github.ref_name }}
